### ISSUE TITLE
'Current Relative Humidity' warning followed by errors after 1.3.4 Homebridge Upgrade 

### ISSUE THREAD

**Issue by SRamsdell1** [bassrock/homebridge-flair#125]
Homebridge v1.3.4
Node v12.14.1
Flair plugin v1.2.7

See logs below ... the issue seems to clutter logs but not have material impact otherwise.

[7/26/2021, 02:48:04] [homebridge-flair] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 02:48:04] [homebridge-flair] Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at FlairRoomPlatformAccessory.updateRoomReadingsFromRoom (/usr/lib/node_modules/homebridge-flair/src/roomPlatformAccessory.ts:157:10)
    at FlairRoomPlatformAccessory.getNewRoomReadings (/usr/lib/node_modules/homebridge-flair/src/roomPlatformAccessory.ts:120:14)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-flair/src/roomPlatformAccessory.ts:69:9)
[7/26/2021, 02:48:04] [Flair] Pushed updated current temperature state for Vesper to HomeKit: 22.6112111111111

**Comment by lukebrannon1** [comment]
Same here

**Comment by gorobotgo** [comment]
Also having this issue, though the stack trace seems to be slightly different from what was originally reported:

`[homebridge-flair] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[17/11/2023, 15:36:49] [homebridge-flair] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentRelativeHumidity.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at Thermostat.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at FlairRoomPlatformAccessory.updateRoomReadingsFromRoom (/var/lib/homebridge/node_modules/homebridge-flair/src/roomPlatformAccessory.ts:161:8)
    at FlairRoomPlatformAccessory.getNewRoomReadings (/var/lib/homebridge/node_modules/homebridge-flair/src/roomPlatformAccessory.ts:132:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by passionatelogic** [comment]
Same error here too
